### ISSUE TITLE
Debian Core 和 Ubuntu Core 的 SSH 连接好像有问题

### ISSUE THREAD

**Issue by Herry-too** [friendlyarm/sd-fuse_rk3328#11]
使用以下固件时无法正常工作：
rk3328-sd-debian-bullseye-core-5.15-arm64-20230404.img
rk3328-sd-friendlycore-lite-focal-5.15-arm64-20230404.img
rk3328-sd-friendlycore-focal-4.19-arm64-20230404.img
具体情况为，可以正常ping通，但是无法进行SSH连接，提示超时。

测试过第三方固件（Armbian），可以正常连接，应该不是板子和SD卡的问题。

**Comment by friendlyarm** [comment]
我的测试了 是可以的，有试过用普通用户吗？即：
ssh pi@IP
默认密码是 pi

**Comment by Herry-too** [comment]
试了下rk3328-sd-debian-bullseye-core-5.15-arm64-20230529.img，可以了，谢谢。
