### ISSUE TITLE
Buildroot Compilation R2S-Plus DTB error

### ISSUE THREAD

**Issue by uruzFR** [friendlyarm/sd-fuse_rk3328#12]
**Hello,**

I have an R2S-Plus and I want to build a custom image with Buildroot for it. I followed this tutorial: [link](https://wiki.friendlyelec.com/wiki/index.php/Buildroot#Introduction_to_Buildroot).

I noticed that when I try to boot with the Buildroot image, I encounter the following error:

```
Found DTB in resource part
Failed to load DTB
Failed to get kernel dtb, ret=-19

```
However, when I try with the official Buildroot repository from Google Drive, I see:

```
Found DTB in resource part
DTB: rk3328-nanopi-r2-rev24.dtb (78034)
```

If you have any ideas or suggestions to resolve this issue, I would greatly appreciate your input.

Thank you!

**Comment by lawrencetg** [comment]
Hi, the kernel code has been updated, pull it up using the following command:
./.repo/repo/repo sync kernel

**Comment by uruzFR** [comment]
**Hi,**

Thank you very much for your reply, it works perfectly! 👍🏻 
Now I have a simple question : Do you consider upgrading the kernel from 4.19 to 6.1 or higher for Buildroot compilation?

Thanks again 🙏

**Comment by friendlyarm** [comment]
> **Hi,**
> 
> Thank you very much for your reply, it works perfectly! 👍🏻 Now I have a simple question : Do you consider upgrading the kernel from 4.19 to 6.1 or higher for Buildroot compilation?
> 
> Thanks again 🙏

There's no 6.1 kernel for buildroot yet, debian-core is paired with the mainline 6.x kernel, but it lacks gpu/vpu support
