### ISSUE TITLE
Buildroot Compilation R2S-Plus Network LED status dosen't work

### ISSUE THREAD

**Issue by uruzFR** [friendlyarm/sd-fuse_rk3328#13]
**Hello,**

I have an R2S-Plus and I built an image with Buildroot for this board, following this tutorial: [link](https://wiki.friendlyelec.com/wiki/index.php/Buildroot#Introduction_to_Buildroot).

My question is : how does the LED status work and why does only the sys LED work and not the other two network LEDs ? Do you have a solution to make these LEDs work ?

Thank you !

**Comment by friendlyarm** [comment]
The method should be the same as for ubuntu core systems (via sys fs operation), see the following documentation:
https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R2S_Plus#Config_status_LEDs

**Comment by uruzFR** [comment]
**Hello,** 
That works on the local installation, but do you know how I can apply these settings directly in Buildroot ?

Thank you !

**Comment by lawrencetg** [comment]
Use the following command to pull updates, and then re-packaged sd-raw image:
./.repo/repo/repo sync device/friendlyelec
./build.sh sd-img

**Comment by uruzFR** [comment]
It works perfectly, thank you
