### ISSUE TITLE
Buildroot BR2_ROOTFS_DEVICE_TABLE Problem

### ISSUE THREAD

**Issue by uruzFR** [friendlyarm/sd-fuse_rk3328#15]
**Hello,**

After few ajustement for my Buildroot OS il found an error. 

I needed to have specific pemission on a folder for a single user. So I activated "BR2_ROOTFS_DEVICE_TABLE="system/device_table.txt" in the file . config . But I don’t see any change in the permits, I have breathed the syntax of the official cosumenation but nothing. (User and group are created & detected)

If you have already encountered this problem or you have an idea I am taking.

**Thank you !**

**Comment by lawrencetg** [comment]
Hi, try making the following changes to scripts/sd-fuse:
```
diff --git a/build-rootfs-img.sh b/build-rootfs-img.sh
index b205f52..afc2feb 100755
--- a/build-rootfs-img.sh
+++ b/build-rootfs-img.sh
@@ -33,7 +33,7 @@ fi

 MKFS_OPTS="-E android_sparse -t ext4 -L rootfs -M /root -b 4096"
 case ${TARGET_OS} in
-friendlywrt* | buildroot*)
+friendlywrt*)
     # set default uid/gid to 0
     MKFS_OPTS="-0 ${MKFS_OPTS}"
     ;;
```

**Comment by uruzFR** [comment]
**Hello,** 

Thank you very much for your help, everything works.

Thanks !

**Comment by uruzFR** [comment]
**Hello,**

Recently, I had to reuse the device table file to modify the permissions of "/sys/devices/platform/gpio-leds/leds/wan_led/trigger" but during the Buildroot compilation, I received this error message: "table='/home/build/buildroot-rk3328/buildroot/output/build/buildroot-fs/device_table.txt' makedevs: line 21: regular file '/home/build/buildroot-rk3328/buildroot/output/target/sys/devices/platform/gpio-leds/leds/wan_led/trigger' does not exist: No such file or directory"

Subsequently, I tried to modify it manually and it works.

Can you help me ?

**Thank you !**

**Comment by uruzFR** [comment]
**Hello,**

Recently, I had to reuse the device table file to modify the permissions of "/sys/devices/platform/gpio-leds/leds/wan_led/trigger" but during the Buildroot compilation, I received this error message: "table='/home/build/buildroot-rk3328/buildroot/output/build/buildroot-fs/device_table.txt' makedevs: line 21: regular file '/home/build/buildroot-rk3328/buildroot/output/target/sys/devices/platform/gpio-leds/leds/wan_led/trigger' does not exist: No such file or directory"

Subsequently, I tried to modify it manually and it works.

Can you help me ?

**Thank you !**
