### ISSUE TITLE
前几天最后的更新编译有问题，提示[ERROR]: error: fail to gen boot.img.

### ISSUE THREAD

**Issue by chobitsos** [friendlyarm/sd-fuse_rk3328#16]
====Building friendlywrt ok!====
[INFO]: Copying friendlywrt23-rk3328/friendlywrt/build_dir/target-aarch64_generic_musl/root-rockchip to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM/  
[INFO]: Applying device/common/ntfs3 to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
[INFO]: Applying device/common/uas to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
[INFO]: Applying device/common/nft-fullcone to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
[INFO]: Applying device/common/emmc-tools to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
[INFO]: Applying device/common/distfeeds to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
[INFO]: Applying device/common/default-settings to friendlywrt23-rk3328/scripts/sd-fuse/out/rootfs.uH90CF7eM  
Pack to resource.img successed!
[INFO]: prepare boot.img ...  
./build.sh: line 309: ./build-boot-img.sh: No such file or directory
[ERROR]: error: fail to gen boot.img. 

看了一下代码，由这个commit里面的[build-boot-img.sh]
(https://github.com/friendlyarm/sd-fuse_rk3328/commit/0b5b748620b14d94692af12750b0474994ee81e0)
被删除导致无法编译
需要切换分支为kernel-5.15.y才能编译，但是就无法使用kernel-6.1.y的内核了
而且小白的话肯定都编译不过去了，不止3328，其他的都有问题

**Comment by friendlyarm** [comment]
谢谢提醒，已经修复了
