### ISSUE TITLE
friendlywrt 镜像 rootfs 的 owner 和 group 异常

### ISSUE THREAD

**Issue by fanck0605** [friendlyarm/sd-fuse_rk3328#2]
使用 build.sh 制作的 friendlywrt 镜像， rootfs 的 owner 和 group 异常，都是编译时的用户名和用户组，openwrt 镜像应该为 root:root，应该是制作镜像的时候导致的问题。[https://github.com/klever1988/nanopi-openwrt/pull/131](https://github.com/klever1988/nanopi-openwrt/pull/131#issuecomment-607948655)

**Comment by friendlyarm** [comment]
多谢反馈，我们跟进一下这个问题

**Comment by friendlyarm** [comment]
此问题已修正，相关提交： https://github.com/friendlyarm/sd-fuse_rk3328/commit/26179830718030c161ae6cfd62f77bb32cbbc10f
